
services:

  db:
    image: postgres:latest  # Use the official Postgres 13 image
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Set the database password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data in a named volume
      - ./postgres/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql  # DDL SQL initialization file
      - ./postgres/dml.sql:/docker-entrypoint-initdb.d/dml.sql  # DML SQL initialization file
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db


# Named volumes to persist PostgreSQL data
volumes:
  pgdata:
