version: "1.0"
services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: jessy9955/school_postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Set the database password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data in a named volume
      - ./postgres/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql  # DDL SQL initialization file
      - ./postgres/dml.sql:/docker-entrypoint-initdb.d/dml.sql  # DML SQL initialization file
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL

  # Backend service (NestJS)
  backend:
    build:
      context: ./back-end/school
      dockerfile: Dockerfile
    image: jessy9955/school_nest
    container_name: nestjs-backend
    restart: always
    ports:
      - "3000:3000"  # Expose port 3000 for accessing the backend
    volumes:
      - ./back-end/school:/src  # Mount the local backend directory to the container
      - /src/node_modules # Persist the node_modules in a volume to avoid reinstalling every time
    environment:
      - NODE_ENV=production  # Set the environment to development
    command: ["npm", "run", "start:prod"]   # Run the application in development mode
    depends_on:
      - db  # Wait for the database service to be available


# Named volumes to persist PostgreSQL data
volumes:
  pgdata:
