name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Unit Test"]  # This should be the name of your first workflow
    types:
      - completed  # Trigger when the first workflow is completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: school_angular_nest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker
        run: |
          echo ---Building and starting up docker---
          docker compose -f ./school_angular_nest/docker-compose_production.yml build --push
          echo --- Completed test cases ---

#      - name: Execute tests in the running services
 #       run: |
  #        docker compose -f ./docker-compose_production.yml exec backend curl http://localhost:300
