name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          path: school_angular_nest

      - name: Build docker
        run: |
          echo ---Building and starting up docker---
          docker compose -f ./school_angular_nest/docker-compose_production.yml up -d
          echo --- Completed test cases ---

      - name: Application health check
        run: |
          docker ps
          docker exec -it nestjs-backend curl http://localhost:3000

#      - name: Execute tests in the running services
 #       run: |
  #        docker compose -f ./docker-compose_production.yml exec backend curl http://localhost:300
