name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Run docker compose
        run: docker-compose -f ./docker-compose_production.yml up -d

      - name: Application health check
        run: |
          docker exec -it nestjs-backend bash
          curl http://localhost:3000

#      - name: Execute tests in the running services
 #       run: |
  #        docker compose -f ./docker-compose_production.yml exec backend curl http://localhost:300
