name: Unit Test

on: [push]
#  workflow_dispatch:
#    push:
#      branches: ["feature/*"]
#      paths:
#        - 'back-end/**'
#        - 'front-end/**'


jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Backend Build and test
        run: |
          docker build --target unittest -t myapp:dev ./back-end/school
          docker run --name test --rm myapp:dev 

      - name: Test Report
        if: always()
        run: |
          echo "========== test ============"
          docker cp $(docker ps -alq):. .
          ls back-end/school/test/report
          mv back-end/school/test/report/ ./report
          ls .
          ls report
          # cat $(find back-end/ -type f -name test-report.html) >> "$GITHUB_STEP_SUMMARY"
          # exit 1

      - name: Test JUnit Report
        id: junit-report
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: 'report/junit.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: JUnit Report to Markdown
        run: |
          echo "${{ steps.junit-report.outputs.detailed_summary }}" > "$GITHUB_STEP_SUMMARY"

      - name: Convert HTML to Markdown
        if: always()
        id: html2markdown
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: report/test-report.html

      - name: Show content of generated markdown file
        if: always()
        continue-on-error: true
        run: |
          echo "### test result ###" > "$GITHUB_STEP_SUMMARY"  
          cat "${{ steps.html2markdown.outputs.markdown-file }}" > "$GITHUB_STEP_SUMMARY"   
        
          


