name: Unit Test

on: [push]
#workflow_dispatch:
#  push:
#    branches: ["feature/*"]
#    paths:
#      - 'back-end/**'
#      - 'front-end/**'

permissions:
  checks: write
  pull-requests: write

jobs:
  backend-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Backend Build and test
        run: |
          docker build --target unittest -t myapp:dev ./back-end/school
          docker run --name test --rm myapp:dev 

      - name: Backend Test Result Copy
        if: always()
        run: |
          docker cp $(docker ps -alq):. .
          ls back-end/school/test/report
          mv back-end/school/test/report/ ./report


      - name: Junit Summary Report
        id: detailReport
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: 'report/junit.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: true
          job_name: 'backend-unit-test'

      - name: Junit Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            report/*.xml

         
        
          


