name: Unit Test

on: [push]
#  workflow_dispatch:
#    push:
#      branches: ["feature/*"]
#      paths:
#        - 'back-end/**'
#        - 'front-end/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Backend Build and test
        continue-on-error: true
        run: |
          docker build --target unittest -t myapp:dev ./back-end/school
          docker run --name test --rm myapp:dev 

      - name: Test Report
        run: |
          echo "========== test ============"
          docker cp $(docker ps -alq):. .
          # cat $(find back-end/ -type f -name test-report.html) >> "$GITHUB_STEP_SUMMARY"
          # exit 1

      - uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Or use "continue-on-error: true" in previous test step
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: back-end/school/test/report

      - uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Or use "continue-on-error: true" in previous test step
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: back-end/school/test/report

      - name: Convert HTML to Markdown
        id: html2markdown
        if: always()
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: "back-end/school/test/report/test-report.html"

      - name: Show content of generated markdown file
        if: always()
        run: |
          cat ${{ steps.html2markdown.outputs.markdown-file }} >> "$GITHUB_STEP_SUMMARY"   
        
      


