name: Unit Test

on: [push]
#  workflow_dispatch:
#    push:
#      branches: ["feature/*"]
#      paths:
#        - 'back-end/**'
#        - 'front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Backend Build and test
        run: |
          docker build --target unittest -t myapp:dev ./back-end/school
          docker run --rm myapp:dev test


      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

